### ISSUE TITLE
Can you make a dark version?

### ISSUE THREAD

**Issue by snakeninja110** [STayinloves/vue-color#1]
Is there any chance you make a dark version?

**Comment by sanxing-chen** [comment]
It's in my todo list. Perhas in two or three months? Be patient to wait, hah.

**Comment by shadowcodex** [comment]
checking back 5 months later ;)

**Comment by sanxing-chen** [comment]
The [dark version](https://marketplace.visualstudio.com/items?itemName=staychan.vue-color-dark) has been published to vs market. Hope you will love it.

**Comment by shadowcodex** [comment]
I'd say that does well. We can close this issue now :)
